### ISSUE TITLE
Valorant fullmaps. 

### ISSUE THREAD

**Issue by coreartz** [Amrsatrio/BlenderUmap#1]
Get this error in the bat file.

Think this is because of the ram but im not 100% sure.
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.util.ArrayList.grow(Unknown Source)
        at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
        at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
        at java.util.ArrayList.add(Unknown Source)
        at me.fungames.jfortniteparse.ue4.assets.objects.UScriptArray.<init>(UScriptArray.kt:29)
        at me.fungames.jfortniteparse.ue4.assets.objects.FPropertyTagType$Companion.readFPropertyTagType(FPropertyTagType.kt:140)
        at me.fungames.jfortniteparse.ue4.assets.objects.FPropertyTag.<init>(FPropertyTag.kt:62)
        at me.fungames.jfortniteparse.ue4.assets.exports.UObject$Companion.deserializeProperties(UObject.kt:67)
        at me.fungames.jfortniteparse.ue4.assets.exports.UObject.<init>(UObject.kt:20)
        at me.fungames.jfortniteparse.ue4.assets.exports.UObject.<init>(UObject.kt:18)
        at me.fungames.jfortniteparse.ue4.assets.Package.readExport(Package.kt:158)
        at me.fungames.jfortniteparse.ue4.assets.Package.<init>(Package.kt:110)
        at me.fungames.jfortniteparse.fileprovider.AbstractFileProvider.loadGameFile(AbstractFileProvider.kt:19)
        at com.tb24.blenderumap.Main.lambda$loadIfNot$2(Main.java:361)
        at com.tb24.blenderumap.Main$$Lambda$2/141289226.invoke(Unknown Source)
        at kotlin.collections.MapsKt__MapsKt.getOrPut(Maps.kt:354)
        at com.tb24.blenderumap.Main.loadIfNot(Main.java:361)
        at com.tb24.blenderumap.Main.loadIfNot(Main.java:353)
        at com.tb24.blenderumap.Main.exportAndProduceProcessed(Main.java:143)
        at com.tb24.blenderumap.Main.main(Main.java:110)
```

**Comment by Amrsatrio** [comment]
Valorant is not tested yet because I don't have the game. I'll test my tool with valorant once I got the game.

**Comment by coreartz** [comment]
This time the batch file dont ended at a error and created the json file.

But when i import to blender i get just this and nothig happen: 
```
bpy.ops.mesh.primitive_cube_add(size=100, enter_editmode=False, location=(0, 0, 0))
bpy.ops.mesh.primitive_cube_add(size=1, enter_editmode=False, location=(0, 0, 0))
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.delete()
bpy.ops.text.run_script()
```

I also send with a log file from the cmd.
[cmd log.txt](https://github.com/Amrsatrio/BlenderUmap/files/4776216/cmd.log.txt)

**Comment by coreartz** [comment]
IDK if this help but here is everything I get from use Umap with a Valorant full map (log and json files).

https://we.tl/t-4loLQt0MMS

**Comment by LRK321** [comment]
Did you fix the issue? If so, what was the solution?

**Comment by filibis** [comment]
Hey @Amrsatrio could you take a look at this issue for Valorant?
@coreartz Have you able to import maps successfully?
