### ISSUE TITLE
Script Failing

### ISSUE THREAD

**Issue by GMatrixGames** [Amrsatrio/BlenderUmap#17]
Hey Amr,

Was just trying to test this out for the first time, and when I went to run the python script in blender, I get this error in the system console: 
```
Traceback (most recent call last):
  File "\umap.py", line 422, in <module>
  File "\umap.py", line 25, in import_umap
IndexError: string index out of range
Error: Python script failed, check the message in the system console```

**Comment by FortniteFevers** [comment]
I get this too.
