### ISSUE TITLE
Problems with a UE4.22 game

### ISSUE THREAD

**Issue by andrewhigh** [Amrsatrio/BlenderUmap#21]
I've been trying to extract a map from another game besides fortnite, but it says it can't find the umap file.
This is the error
```
FileProvider: WARN: Uncaught exception while loading pak file banks.pak
java.nio.BufferUnderflowException: null
        at java.nio.Buffer.nextGetIndex(Unknown Source) ~[?:1.8.0_261]
        at java.nio.HeapByteBuffer.getLong(Unknown Source) ~[?:1.8.0_261]
        at me.fungames.jfortniteparse.ue4.pak.reader.FBytePakArchive.readInt64(FBytePakArchive.kt:71) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.objects.FPakCompressedBlock.<init>(FPakCompressedBlock.kt:15) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.objects.FPakEntry.<init>(FPakEntry.kt:79) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.readIndexLegacy(PakFileReader.kt:442) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.readIndex(PakFileReader.kt:399) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.fileprovider.PakFileProvider$submitKeysAsync$$inlined$forEach$lambda$1.invokeSuspend(PakFileProvider.kt:42) [BlenderUmap.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [BlenderUmap.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [BlenderUmap.jar:?]
FileProvider: WARN: Uncaught exception while loading pak file AC2-WindowsNoEditor.pak
me.fungames.jfortniteparse.exceptions.ParserException: Invalid String length '1633971823'
FPakArchive Info: pos 10739791185, stopper 10762193998
        at me.fungames.jfortniteparse.ue4.reader.FArchive.readString(FArchive.kt:121) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.objects.FPakEntry.<init>(FPakEntry.kt:49) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.readIndexLegacy(PakFileReader.kt:442) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.readIndex(PakFileReader.kt:399) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.fileprovider.PakFileProvider$submitKeysAsync$$inlined$forEach$lambda$1.invokeSuspend(PakFileProvider.kt:42) [BlenderUmap.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [BlenderUmap.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [BlenderUmap.jar:?]
FileProvider: WARN: File ac2/content/maps/nurburgring.umap not found
FileProvider: WARN: File ac2/content/maps/nurburgring.umap not found
```

The game is on ue4.22 and the AES is also correct,  I can extract assets using gildors umodel.

This is my config:
```
{
  "_Documentation": "https://github.com/Amrsatrio/BlenderUmap/blob/master/README.md",
  "PaksDirectory": "C:\\Program Files\\Steam\\steamapps\\common\\Assetto Corsa Competizione\\AC2\\Content\\Paks",
  "UEVersion": "GAME_UE4_22",
  "EncryptionKeys": [
    {
      "Guid": "00000000000000000000000000000000",
      "Key": "670AF6D953018EB22676D3031A6613C3C6F5D32DFA643B45D4E07437DB8DEFE3"
    }
  ],
  "bReadMaterials": true,
  "bUseUModel": true,
  "UModelAdditionalArgs": "",
  "bDumpAssets": true,
  "ExportPackage": "/AC2/Content/Maps/nurburgring.umap"
}
```

**Comment by Amrsatrio** [comment]
This is an issue on the JFortniteParse side, where there is no guarantees that it is able to read paks of games other than Fortnite and Valorant
