### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by kastrom3** [Amrsatrio/BlenderUmap#38]
I filled in the config, but it gives an error on startup. I understand so that some problem with the key, but in UE Viewer it works great.

  **"EncryptionKeys":** [c7B2DvPsRgH9Ve0BjGJKzBIeCIeoSTtXIMKapnDWQqKvico7d9PFsJ4XYwDuhbjV],

**Error:**
```
[2020.12.19-09.39.12:093]BlenderUmap: INFO: Reading config file C:\Users\kastrom\Desktop\BlenderUmap\config.json
[2020.12.19-09.39.12:155]BlenderUmap: ERROR: An unexpected error has occurred, please report
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 5 column 22 path $.EncryptionKeys[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[BlenderUmap.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[BlenderUmap.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[BlenderUmap.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[BlenderUmap.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[BlenderUmap.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[BlenderUmap.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[BlenderUmap.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:870) ~[BlenderUmap.jar:?]
	at com.tb24.blenderumap.Main.main(Main.java:75) [BlenderUmap.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 5 column 22 path $.EncryptionKeys[0]
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) ~[BlenderUmap.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[BlenderUmap.jar:?]
	... 8 more
```

**Comment by Amrsatrio** [comment]
The tool only recognizes keys in hex (0xABCDEF) like umodel and base64 which is used by Epic in the editor. So that's not a valid key format

**Comment by kastrom3** [comment]
Okay, thank you. I will think about how to get a key of a suitable format.

**Comment by kastrom3** [comment]
If someone is also looking for AES Key for Absolver, then here is `0x0000803F0000803F0000803F0050C3C700606A460000803F0000003F2FDDE43E`
