### ISSUE TITLE
Game not displaying mount point, resulting in package not being found

### ISSUE THREAD

**Issue by Markimoot** [Amrsatrio/BlenderUmap#4]
The game in question is Five Nights at Freddy's: Help Wanted and it's a 4.23 game.

`[2020.06.13-17.31.48:542]PakFile: INFO: Pak freddys-WindowsNoEditor.pak: 26135 files (8142 encrypted), mount point: "", version 8
[2020.06.13-17.31.48:595]PakFile: INFO: Pak HalloweenDLCfreddys-WindowsNoEditor.pak: 13661 files (4669 encrypted), mount point: "", version 8

Exporting Game/Scenes/MainMenuWithShowtime/Showtime.umap
WARNING: Requested package Game/Scenes/MainMenuWithShowtime/Showtime.umap was not found
java.lang.NullPointerException
        at com.tb24.blenderumap.Main.exportAndProduceProcessed(Main.java:144)
        at com.tb24.blenderumap.Main.main(Main.java:110)
Press any key to continue . . .`

I'm assuming based on the fact the "mount point" part isn't showing up, it's resulting in the package not being associated to any folders as it's not loading any folders.

**Comment by Amrsatrio** [comment]
This happens most likely because the underlying lib can't figure out the game name. Have you tried including a slash before `Game`?

**Comment by Markimoot** [comment]
Tried that, still results in the same issue. This is with a different umap but the one from the OG post also doesn't work with this method

```
[2020.06.14-02.36.20:058]PakFile: INFO: Pak freddys-WindowsNoEditor.pak: 26135 files (8142 encrypted), mount point: "", version 8

Exporting /Game/Scenes/Office_Games/NightGuard_Office02.umap
WARNING: Requested package /Game/Scenes/Office_Games/NightGuard_Office02.umap was not found
java.lang.NullPointerException
        at com.tb24.blenderumap.Main.exportAndProduceProcessed(Main.java:144)
        at com.tb24.blenderumap.Main.main(Main.java:110)
Press any key to continue . . .
```

**Comment by Amrsatrio** [comment]
This is weird, and sadly I can't test that because I don't own the game and don't want to shell out money just to make my tool or the lib in general compatible with it.

**Comment by Markimoot** [comment]
If it helps, I've found another game that has the same issue but is free on Steam since it's a demo. Currently the Hello Guest demo gives me this:
```
[2020.06.14-16.44.55:699]PakFile: INFO: Pak HelloGuest-WindowsNoEditor.pak: 11028 files (0 encrypted), mount point: "", version 8

Exporting Game/Maps/MainLevel/MainLevel.umap
WARNING: Requested package Game/Maps/MainLevel/MainLevel.umap was not found
java.lang.NullPointerException
        at com.tb24.blenderumap.Main.exportAndProduceProcessed(Main.java:144)
        at com.tb24.blenderumap.Main.main(Main.java:110)
Press any key to continue . . .
```
I would assume if you found the issue that was causing it to happen with this and fixed it, then everything else would work fine.
https://store.steampowered.com/app/1321680/Hello_Guest/

**Comment by Tectors** [comment]
Same thing happens with Fortnite, I've as well set the game version to 3 for the latest version of Unreal Engine.

Path is /Game/Athena/Apollo/Maps/Buildings/3x3/Apollo_3x3_Power_Tower_b.umap.
