### ISSUE TITLE
Illegal key size or default parameters

### ISSUE THREAD

**Issue by iNether** [Amrsatrio/BlenderUmap#41]
VALORANT
**console output**
```
BlenderUmap: INFO: Reading config file G:\DataMine\_umodel-map\config.json
FileProvider: WARN: Uncaught exception while loading pak file pakchunk1_s34-WindowsClient.pak
java.security.InvalidKeyException: Illegal key size or default parameters
        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026) ~[?:1.8.0_121]
        at javax.crypto.Cipher.implInit(Cipher.java:801) ~[?:1.8.0_121]
        at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[?:1.8.0_121]
        at javax.crypto.Cipher.init(Cipher.java:1249) ~[?:1.8.0_121]
        at javax.crypto.Cipher.init(Cipher.java:1186) ~[?:1.8.0_121]
        at me.fungames.jfortniteparse.encryption.aes.Aes.decryptData(Aes.kt:38) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.readIndexLegacy(PakFileReader.kt:732) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.ue4.pak.PakFileReader.readIndex(PakFileReader.kt:382) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.fileprovider.PakFileProvider.mount(PakFileProvider.kt:83) ~[BlenderUmap.jar:?]
        at me.fungames.jfortniteparse.fileprovider.PakFileProvider$submitKeysAsync$1.invokeSuspend(PakFileProvider.kt:63) [BlenderUmap.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [BlenderUmap.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [BlenderUmap.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [BlenderUmap.jar:?]
BlenderUmap: INFO: Object not found
```

Whether the files are in the original folder (for me it is F:\9_games\Riot Games\VALORANT\live\ShooterGame\Content\Paks) or not - it doesn't matter

**config.json** // Here I use 4.24, because with experiments, I found that the Valorant was updated to 4.24 version (For example, skelmeshes cannot be opened by UModel with 4.23/4.22 (as recommended by author) but everything else opens, skelmeshes (and any other things) can be opened only with 4.24). Any other versions (4.22-4.26) also do not work for UMap
```
{
  "_Documentation": "https://github.com/Amrsatrio/BlenderUmap/blob/master/README.md",
  "PaksDirectory": "G:\\DataMine\\valorant\\pack",
  "UEVersion": "GAME_UE4_24",
  "EncryptionKeys": [
    {
      "Guid": "00000000000000000000000000000000",
      "Key": "0x4BE71AF2459CF83899EC9DC2CB60E22AC4B3047E0211034BBABE9D174C069DD6"
    }
  ],
  "bDumpAssets": false,
  "ObjectCacheSize": 100,
  "bReadMaterials": true,
  "bExportToDDSWhenPossible": false,
  "bExportBuildingFoundations": false,
  "bUseUModel": false,
  "UModelAdditionalArgs": "",
  "ExportPackage": "/Game/Maps/Ascent/Ascent_Art_A.umap"
}
```

Also tried with `FileName` instead of `Guid` with mapping all of the paks + keys. It doesn't work
I also tried non-HEX key, got an error `Invalid AES key length: 48 bytes`

P.S. umodel and fmodel works fine with these paks

**Comment by Amrsatrio** [comment]
That key format, `0x4BE71AF2459CF83899EC9DC2CB60E22AC4B3047E0211034BBABE9D174C069DD6`, is already correct, and for valorant the author of the lib suggested that you should use GAME_VALORANT. Might sound weird but that's it. https://github.com/FabianFG/JFortniteParse#supported-games

**Comment by iNether** [comment]
Same error with GAME_VALORANT and GAME_UE4_LATEST

**Comment by iNether** [comment]
Reinstalled Java, although I had it with auto-updates, and issue was gone.

**Comment by iNether** [comment]
Reinstalled Java, although I had it with auto-updates, and issue was gone
